/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaiterRouteImport } from './routes/waiter'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderTrackingIdRouteImport } from './routes/order-tracking.$id'
import { Route as OrderConfirmationIdRouteImport } from './routes/order-confirmation.$id'
import { Route as ItemIdRouteImport } from './routes/item.$id'

const WaiterRoute = WaiterRouteImport.update({
  id: '/waiter',
  path: '/waiter',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTrackingIdRoute = OrderTrackingIdRouteImport.update({
  id: '/order-tracking/$id',
  path: '/order-tracking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationIdRoute = OrderConfirmationIdRouteImport.update({
  id: '/order-confirmation/$id',
  path: '/order-confirmation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/kitchen': typeof KitchenRoute
  '/loyalty': typeof LoyaltyRoute
  '/manager': typeof ManagerRoute
  '/menu': typeof MenuRoute
  '/waiter': typeof WaiterRoute
  '/item/$id': typeof ItemIdRoute
  '/order-confirmation/$id': typeof OrderConfirmationIdRoute
  '/order-tracking/$id': typeof OrderTrackingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/kitchen': typeof KitchenRoute
  '/loyalty': typeof LoyaltyRoute
  '/manager': typeof ManagerRoute
  '/menu': typeof MenuRoute
  '/waiter': typeof WaiterRoute
  '/item/$id': typeof ItemIdRoute
  '/order-confirmation/$id': typeof OrderConfirmationIdRoute
  '/order-tracking/$id': typeof OrderTrackingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/kitchen': typeof KitchenRoute
  '/loyalty': typeof LoyaltyRoute
  '/manager': typeof ManagerRoute
  '/menu': typeof MenuRoute
  '/waiter': typeof WaiterRoute
  '/item/$id': typeof ItemIdRoute
  '/order-confirmation/$id': typeof OrderConfirmationIdRoute
  '/order-tracking/$id': typeof OrderTrackingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/kitchen'
    | '/loyalty'
    | '/manager'
    | '/menu'
    | '/waiter'
    | '/item/$id'
    | '/order-confirmation/$id'
    | '/order-tracking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/kitchen'
    | '/loyalty'
    | '/manager'
    | '/menu'
    | '/waiter'
    | '/item/$id'
    | '/order-confirmation/$id'
    | '/order-tracking/$id'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/kitchen'
    | '/loyalty'
    | '/manager'
    | '/menu'
    | '/waiter'
    | '/item/$id'
    | '/order-confirmation/$id'
    | '/order-tracking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  KitchenRoute: typeof KitchenRoute
  LoyaltyRoute: typeof LoyaltyRoute
  ManagerRoute: typeof ManagerRoute
  MenuRoute: typeof MenuRoute
  WaiterRoute: typeof WaiterRoute
  ItemIdRoute: typeof ItemIdRoute
  OrderConfirmationIdRoute: typeof OrderConfirmationIdRoute
  OrderTrackingIdRoute: typeof OrderTrackingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiter': {
      id: '/waiter'
      path: '/waiter'
      fullPath: '/waiter'
      preLoaderRoute: typeof WaiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-tracking/$id': {
      id: '/order-tracking/$id'
      path: '/order-tracking/$id'
      fullPath: '/order-tracking/$id'
      preLoaderRoute: typeof OrderTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$id': {
      id: '/order-confirmation/$id'
      path: '/order-confirmation/$id'
      fullPath: '/order-confirmation/$id'
      preLoaderRoute: typeof OrderConfirmationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  KitchenRoute: KitchenRoute,
  LoyaltyRoute: LoyaltyRoute,
  ManagerRoute: ManagerRoute,
  MenuRoute: MenuRoute,
  WaiterRoute: WaiterRoute,
  ItemIdRoute: ItemIdRoute,
  OrderConfirmationIdRoute: OrderConfirmationIdRoute,
  OrderTrackingIdRoute: OrderTrackingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
